# Zadanie 1 Ernest Mgłosiek 165 A2

In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Tworzenie tablicy z zakresem

In [3]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [4]:
np.repeat(5,10)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [6]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
2.5 * np.random.randn(2, 4) + 3

array([[3.17020257, 4.50857725, 5.59792717, 5.12131457],
       [2.53923773, 5.6102688 , 0.75114843, 2.74231493]])

In [2]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [3]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [7]:
random = np.random.random((5,5))*25

In [8]:
print(random)

[[ 7.66150244 24.44237471 19.87962561 15.26553273 12.11503176]
 [16.45518731 18.44013075  3.928796   18.81575729  0.17609809]
 [ 3.71668544 14.78189281  6.48075724 22.80660511  3.15771748]
 [ 9.91455601 20.04706596  4.52036338  2.62454694  9.05497801]
 [17.84651833 22.80906092 14.68963489 16.48315694  7.77023032]]


In [9]:
print(random.sum())

313.88380646868814


In [10]:
print(random.sum()/25)

12.555352258747526


In [11]:
print(np.std(random))

7.130396019100952


In [12]:
array=[]

In [13]:
for x in range(0,5):
    array.append(random[:,x].sum())
array

[55.594449532229525,
 100.52052515453656,
 49.49917711580971,
 75.99559900764031,
 32.27405565847204]

In [14]:
var  = np.random.random((5,5))*100

# Mediana

In [15]:
print(np.median(var))

44.346181638889114


# Najmniejsza Liczba:

In [17]:
print(np.min(var))

5.563999186048729


# Liczba największa

In [18]:
print(np.max(var))

98.59412145892847


# Transpozycja

In [19]:
random_random = np.random.random((5,8))

In [20]:
print(random_random)

[[8.23188006e-01 8.92484767e-01 5.37399346e-01 7.61346021e-01
  4.76589051e-01 6.90633346e-01 2.03264203e-01 7.90923366e-01]
 [2.70564743e-01 2.32128551e-04 9.65344326e-01 6.62171934e-01
  3.56516252e-01 9.68611079e-01 2.82709280e-01 7.17999401e-01]
 [7.04053007e-01 7.83836673e-01 7.62855612e-01 9.62418257e-01
  2.53276358e-01 8.24486505e-01 2.16693677e-01 9.50907685e-01]
 [7.93201348e-01 9.54019489e-01 6.93101118e-01 9.80719737e-01
  8.47145601e-01 9.75708576e-01 9.00431050e-01 5.49237541e-01]
 [4.55852869e-01 9.71338376e-01 1.70405562e-01 2.05208245e-01
  2.03969783e-01 6.79779759e-01 1.26563304e-01 9.47922227e-01]]


In [21]:
print(np.transpose(random_random))

[[8.23188006e-01 2.70564743e-01 7.04053007e-01 7.93201348e-01
  4.55852869e-01]
 [8.92484767e-01 2.32128551e-04 7.83836673e-01 9.54019489e-01
  9.71338376e-01]
 [5.37399346e-01 9.65344326e-01 7.62855612e-01 6.93101118e-01
  1.70405562e-01]
 [7.61346021e-01 6.62171934e-01 9.62418257e-01 9.80719737e-01
  2.05208245e-01]
 [4.76589051e-01 3.56516252e-01 2.53276358e-01 8.47145601e-01
  2.03969783e-01]
 [6.90633346e-01 9.68611079e-01 8.24486505e-01 9.75708576e-01
  6.79779759e-01]
 [2.03264203e-01 2.82709280e-01 2.16693677e-01 9.00431050e-01
  1.26563304e-01]
 [7.90923366e-01 7.17999401e-01 9.50907685e-01 5.49237541e-01
  9.47922227e-01]]


# Operacje na macierzach

In [28]:
m_a = np.array(([1,2,3],([4,5,6])))
m_b = np.array(([7,8,9],([10,11,12])))

In [29]:
print(m_a + m_b)

[[ 8 10 12]
 [14 16 18]]


In [33]:
m_a = np.array(([1,2],([4,5]),([6,7])))
m_b = np.array(([7,8,3],([10,11,3])))

In [34]:
print(m_a)
print(m_b)

[[1 2]
 [4 5]
 [6 7]]
[[ 7  8  3]
 [10 11  3]]


In [35]:
print(np.matmul(m_a,m_b))

[[ 27  30   9]
 [ 78  87  27]
 [112 125  39]]


In [36]:
print(np.multiply(m_a,np.transpose(m_b)))

[[ 7 20]
 [32 55]
 [18 21]]
